config/routes.rb
Rails.application.routes.draw do
  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products do
    get :who_bought, on: :member
  end

  root 'store#index', as: 'store'

end

app/models/order.rb
class Order < ActiveRecord::Base
  PAYMENT_TYPES = ["Check", "Credit card", "Purchare order"]
  has_many :line_items, dependent: :destroy
  # ...
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.paginate(page: params[:page],per_page: 10).order('created_at DESC')
    # @orders = Order.all
    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @cart = current_cart
    if @cart.line_items.empty?
      redirect_to store_url, notice: "Your cart is empty"
      return
    end

    @order = Order.new
    respond_to do |format|
      format.html #new.html.haml
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(current_cart)

    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        OrderNotifier.received(@order).deliver
        format.html { redirect_to store_url, notice: 'Thank you for your order.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :address, :email, :pay_type)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
= form_for @order do |f|
  - if @order.errors.any?
    #error_explanation
      %h2= "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      %ul
        - @order.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name, size: 40
  .field
    = f.label :address
    = f.text_area :address, rows: 3, cols: 40
  .field
    = f.label :email
    = f.text_field :email, size: 40
  .field
    = f.label :pay_type
    = f.select :pay_type, Order::PAYMENT_TYPES, prompt: 'Select a payment method'
  .actions
    = f.submit 'Place Order'

app/views/orders/edit.html.haml
%h1 Editing order

= render 'form'

= link_to 'Show', @order
\|
= link_to 'Back', orders_path

app/views/orders/index.html.haml
%h1 Listing orders

%table
  %tr
    %th Name
    %th Address
    %th Email
    %th Pay type
    %th
    %th
    %th

  - @orders.each do |order|
    %tr
      %td= order.name
      %td= order.address
      %td= order.email
      %td= order.pay_type
      %td= link_to 'Show', order
      %td= link_to 'Edit', edit_order_path(order)
      %td= link_to 'Destroy', order, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Order', new_order_path
%p= will_paginate @orders

app/views/orders/new.html.haml
.depot_form
  %fieldset
    %legend Please Enter Your Details
    = render 'form'

app/views/orders/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @order.name
%p
  %b Address:
  = @order.address
%p
  %b Email:
  = @order.email
%p
  %b Pay type:
  = @order.pay_type

= link_to 'Edit', edit_order_path(@order)
\|
= link_to 'Back', orders_path