config/routes.rb
Rails.application.routes.draw do
  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products do
    get :who_bought, on: :member
  end

  root 'store#index', as: 'store'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @cart = current_cart
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_url }
        format.js {@current_item = @line_item}
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.haml
= form_for @line_item do |f|
  - if @line_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@line_item.errors.count, "error")} prohibited this line_item from being saved:"
      %ul
        - @line_item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :product_id
    = f.number_field :product_id
  .field
    = f.label :cart_id
    = f.number_field :cart_id
  .actions
    = f.submit 'Save'

app/views/line_items/_line_item.html.haml
%tr{:id => (line_item == @current_item ? 'current_item' : nil)}
  %td #{line_item.quantity}&times;
  %td= line_item.product.title
  %td.item_price= number_to_currency(line_item.total_price)

app/views/line_items/_line_item.text.haml
= sprintf("%2d x %s", line_item.quantity, truncate(line_item.product.title, length: 50))

app/views/line_items/create.js.haml
$('#notice').hide();

if ($('#cart tr').length == 1){$('#cart').show('blind', 400);}

$('#cart').html("#{j render @cart}");

$('#current_item').css({'background-color': '#88ff88'}).animate({'background-color':'#114411'}, 1000);

app/views/line_items/edit.html.haml
%h1 Editing line_item

= render 'form'

= link_to 'Show', @line_item
\|
= link_to 'Back', line_items_path

app/views/line_items/index.html.haml
%h1 Listing line_items

%table
  %tr
    %th Product
    %th Cart
    %th
    %th
    %th

  - @line_items.each do |line_item|
    %tr
      %td= line_item.product_id
      %td= line_item.cart_id
      %td= link_to 'Show', line_item
      %td= link_to 'Edit', edit_line_item_path(line_item)
      %td= link_to 'Destroy', line_item, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Line item', new_line_item_path

app/views/line_items/new.html.haml
%h1 New line_item

= render 'form'

= link_to 'Back', line_items_path

app/views/line_items/show.html.haml
%p#notice= notice

%p
  %b Product:
  = @line_item.product_id
%p
  %b Cart:
  = @line_item.cart_id

= link_to 'Edit', edit_line_item_path(@line_item)
\|
= link_to 'Back', line_items_path